# Generated by Django 3.2.3 on 2021-05-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=364, unique=True),
        ),
    ]
