# Generated by Django 3.2.3 on 2021-05-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0002_alter_words_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=364),
        ),
    ]
