# Generated by Django 3.2.4 on 2021-06-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0003_alter_words_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsAz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=364)),
                ('translation', models.CharField(max_length=364)),
            ],
        ),
    ]
